title: Billy's blog
author: Prince Billy Graham Karmoker
email: princebillygk@gmail.com
description: >
  Revision your programming language knowledge. Come here before starting a new project to refresh your knowledge.
baseurl: "/myblogs"
url: "https://princebillygk.github.io"

show_excerpts: false

# social
github_username: princebillygk
linkedin_username: princebillygk

# Build settings
theme: minima
minima: 
  skin: dark

collections:
  snippets:
    output: true
  notes:
     output: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# comment enable
disqus:
  shortname: billys-blog-1

## header navigation configure
header_pages: 
  - notes.markdown
  - snippets.markdown
  - about.markdown

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Readme.md
  - blog.code-workspace
  - docker-compose.yml
