version: "3.8"
# export JEKYLL_VERSION=3.8
# docker run --rm \
#   --volume="$PWD:/srv/jekyll" \
#   -it jekyll/builder:$JEKYLL_VERSION \
#   jekyll build

services:
  site:
    image: jekyll/jekyll
    command: jekyell serve --livereload --verbose
    volumes: 
      - ./:/srv/jekyll
      - ./cache:/usr/local/bundle
    ports:
      - 4000:4000
    environment:
      JEKYLL_ENV: production


